version: "{build}"
skip_tags: true
clone_folder: c:\gopath\src\github.com\lifei6671\godoc
clone_depth: 1

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.8
  matrix:
    - tbs_arch: "x86"
      tbs_tools: "mingw"
      tbs_static_runtime: 1
      GOARCH: 386

    - tbs_arch: "x64"
      tbs_tools: "mingw"
      tbs_static_runtime: 1
      GOARCH: amd64

build: false
deploy: true

install:

  - ps: if($env:tbs_tools -eq 'mingw' -and $env:tbs_arch -eq 'x64')
        {
            Start-FileDownload "http://libgd.blob.core.windows.net/mingw/x86_64-4.9.1-release-posix-seh-rt_v3-rev1.7z" -FileName mingw_x86_64.7z;
            7z x -oC:\ mingw_x86_64.7z | out-null;
        }
  - ps: if($env:tbs_tools -eq 'mingw' -and $env:tbs_arch -eq 'x86')
        {
            Start-FileDownload "http://libgd.blob.core.windows.net/mingw/i686-4.9.1-release-posix-dwarf-rt_v3-rev1.7z" -FileName mingw_x86.7z;
            7z x -oC:\ mingw_x86.7z | out-null;
        }
  - set GO_ENABLED=1
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get -d ./...

build_script:
  - if [%tbs_tools%]==[mingw] if [%tbs_arch%]==[x86] SET PATH=C:\mingw32\bin;%PATH%
  - if [%tbs_tools%]==[mingw] if [%tbs_arch%]==[x64] SET PATH=C:\mingw64\bin;%PATH%
  - go build -v -o "godoc_windows_%GOARCH%.exe" -ldflags="-w -X github.com/lifei6671/godoc/conf.VERSION=%APPVEYOR_REPO_TAG_NAME% -X 'github.com/lifei6671/godoc/conf.BUILD_TIME=`date`' -X 'conf.GO_VERSION=`github.com/lifei6671/godoc/go version`'"
  - rd /q /f /s commands controllers models modules data routers tasks vendor docs search utils graphics .git Godeps uploads/* .gitignore .travis.yml Dockerfile gide.yaml LICENSE main.go README.md conf/enumerate.go conf/mail.go install.lock *.md
  - 7z a -t7z -r godoc_windows_%GOARCH%.7z conf/app.conf static/* godoc_windows_%GOARCH%.exe views/* database/* logs/* uploads/*
test_script:
  - godoc_windows_%GOARCH%.exe version
  - dir

notifications:
  - provider: Email
    to:
      - lifei6671@163.com
    on_build_success: false

deploy:
  - provider: GitHub
    name: production
    auth_token:
        secure:
    draft: false
    artifact:
    on:
      branch: master
      appveyor_repo_tag: true