version: "{build}"
skip_tags: true
clone_folder: c:\gopath\src\github.com\lifei6671\godoc
clone_depth: 1

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.8
  matrix:
    - tbs_arch: "x86"
      tbs_tools: "mingw"
      tbs_static_runtime: 1

    - tbs_arch: "x64"
      tbs_tools: "mingw"
      tbs_static_runtime: 1

build: false
deploy: true

install:

  - ps: if($env:tbs_tools -eq 'mingw' -and $env:tbs_arch -eq 'x64')
        {
            Start-FileDownload "http://libgd.blob.core.windows.net/mingw/x86_64-4.9.1-release-posix-seh-rt_v3-rev1.7z";
            7z x -oC:\ x86_64-4.9.1-release-posix-seh-rt_v3-rev1.7z | out-null;
            set PATH=%PATH%;c:\mingw64\bin;
        }
  - ps: if($env:tbs_tools -eq 'mingw' -and $env:tbs_arch -eq 'x64')
        {
            Start-FileDownload "http://libgd.blob.core.windows.net/mingw/i686-4.9.1-release-posix-seh-rt_v3-rev1.7z";
            7z x -oC:\ x86_64-4.9.1-release-posix-seh-rt_v3-rev1.7z | out-null;
            set PATH=%PATH%;c:\mingw32\bin;
        }
  - set GO_ENABLED=1
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get -d ./...

test_script:
  - go build -x -v -tags "pam" -ldflags "-w"

notifications:
  - provider: Email
    to:
      - lifei6671@163.com
    on_build_success: false